### ISSUE TITLE
Newlines in serverStartMessage?

### ISSUE THREAD

**Issue by ColinTheShark** [kraftwerk28/spigot-tg-bridge#12]
Title says it all basically.

Is there a way to add a newline to the `serverStartMessage` option, without the content being send as the literal characters that represent it?

```yaml
serverStartMessage: 'Server started.\nJoin at <code>IP HERE</code>'
```
Using the above config sends the message as shown left, even though I'd expect it to be sent like on the right (re-enactment)

| Actual result | Expected Result |
| - | - |
| ![](https://i.imgur.com/thWbb8e.png) | ![](https://i.imgur.com/npRmmDO.png) |

**Comment by kraftwerk28** [comment]
Thanks for the issue! Will fix it asap

**Comment by kraftwerk28** [comment]
@ColinTheShark you can follow [yaml spec](https://yaml-multiline.info/) and try writing your config like this:
```yaml
serverStartMessage: |-
  Server started.
  Join at ...
```
This should work, I hope

**Comment by ColinTheShark** [comment]
> ```yaml
> serverStartMessage: |-
>   Server started.
>   Join at ...
> ```

This works wonderfully, thank you :D 
![](https://i.imgur.com/2VwFx7L.png)

<details><summary>Snippet from my current config</summary>

```yaml
chats:
  - -100123456789
serverStartMessage: |-
    Server started.
    Join at <code>IP HERE</code>
serverStopMessage: 'Server stopped.'
```
</details>
